
openapi: 3.1.0
info:
  version: 1.0.0
  title: ContactsApp
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    App for collecting, creating, editing, removing contacts. With authentication and authorization and possibility to reset your password.
tags:
  - name: Phone book
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3040
  - url: https://phonebook-db-d0ot.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
